---
Name: silverstripe-custom-cms-logo
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - XD\CustomCMSLogo\Extensions\SiteConfigExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'vendor/xddesigners/silverstripe-custom-cms-logo/client/dist/styles/customcmslogo.css'